'use client'

import { useEffect, useState } from 'react'
import { BookOpen, Check, ChevronRight, Clock3, Eye, Gamepad2, History, LockKeyhole, Menu, RotateCcw, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'

type Screen = 'home' | 'oan' | 'ven' | 'nhip' | 'history'
type Session = { chapter:number; oan:number; hieu:number; usedVen:number[]; history:string[] }
type Chapter = { n:number; title:string; short:string; theme:string }
type Oan = { id:string; chapter:number; title:string; scene:string; prompt:string; code:string }

const chapters:Chapter[] = [
 {n:1,title:'Làng quê khởi sự',short:'Khởi sự',theme:'Những điều chưa được nói'},
 {n:2,title:'Rời làng vướng oan',short:'Vướng oan',theme:'Khi lời đồn đi trước sự thật'},
 {n:3,title:'Mầu lên chùa',short:'Lên chùa',theme:'Một lựa chọn không dễ dàng'},
 {n:4,title:'Oan Thai nuôi trẻ',short:'Nuôi trẻ',theme:'Nhìn lại điều đã xảy ra'},
 {n:5,title:'Giác ngộ',short:'Giác ngộ',theme:'Khi mọi mảnh ghép tìm thấy nhau'},
]
const oans:Oan[] = [
 {id:'oan-01',chapter:1,title:'Tiếng gọi bên giếng',scene:'Làng quê khởi sự',prompt:'Một lời nói bị nghe thiếu. Hãy nhìn lại tình huống trước khi phán xét.',code:'1842'},
 {id:'oan-02',chapter:1,title:'Chiếc nón bị bỏ quên',scene:'Làng quê khởi sự',prompt:'Một vật nhỏ kéo theo một hiểu lầm lớn.',code:'2716'},
 {id:'oan-03',chapter:2,title:'Lời đồn qua bến nước',scene:'Rời làng vướng oan',prompt:'Tin truyền miệng đã làm thay đổi cách mọi người nhìn nhân vật.',code:'4398'},
]
const evidence = [
 {id:'e1',title:'Lời kể của nhân vật',text:'Nhân vật nói lại điều mình đã nhìn thấy, nhưng giọng kể bị ngắt giữa chừng.',important:true},
 {id:'e2',title:'Dấu vết bên giếng',text:'Chiếc gáo đặt sai chỗ cho thấy có người đã đến trước đó.',important:true},
 {id:'e3',title:'Lời đồn trong xóm',text:'Một người nghe lại câu chuyện từ người khác, không trực tiếp chứng kiến.',important:false},
 {id:'e4',title:'Màu áo hôm ấy',text:'Chi tiết dễ nhớ nhưng chưa đủ để kết luận ai đúng, ai sai.',important:false},
]
const initial:Session={chapter:1,oan:0,hieu:0,usedVen:[],history:[]}
function load(){if(typeof window==='undefined')return initial;try{return JSON.parse(localStorage.getItem('chieu-che-session')||'')}catch{return initial}}
function Kicker({children}:{children:React.ReactNode}){return <p className="kicker">{children}</p>}
function App(){const [session,setSession]=useState<Session>(initial);const [screen,setScreen]=useState<Screen>('home');const [menu,setMenu]=useState(false);useEffect(()=>setSession(load()),[]);useEffect(()=>{if(typeof window!=='undefined')localStorage.setItem('chieu-che-session',JSON.stringify(session))},[session]);const chapter=chapters[session.chapter-1];const oan=oans.find(x=>x.chapter===session.chapter)||oans[0];return <div className="companion"><header className="topbar"><button className="brand" onClick={()=>setScreen('home')}><span className="brand-mark">CC</span><span><b>CHIẾU CHÈO</b><small>SƯƠNG OAN · DIGITAL COMPANION</small></span></button><nav><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}>BẢNG ĐIỀU KHIỂN</button><button className={screen==='history'?'active':''} onClick={()=>setScreen('history')}>HÀNH TRÌNH</button><button className={screen==='ven'?'active':''} onClick={()=>setScreen('ven')}>AI VÉN MÀN</button></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Mở menu"><Menu/></button></header>{menu&&<div className="mobile-menu"><button onClick={()=>{setScreen('home');setMenu(false)}}>Bảng điều khiển<ChevronRight/></button><button onClick={()=>{setScreen('history');setMenu(false)}}>Hành trình của tôi<ChevronRight/></button><button onClick={()=>{setScreen('ven');setMenu(false)}}>AI Vén Màn<ChevronRight/></button></div>}<main>{screen==='home'&&<Home session={session} chapter={chapter} start={()=>setScreen('oan')} ven={()=>setScreen('ven')} nhip={()=>setScreen('nhip')}/>} {screen==='oan'&&<OanFlow card={oan} session={session} update={setSession} back={()=>setScreen('home')}/>} {screen==='ven'&&<VenFlow chapter={session.chapter} locked={session.usedVen.includes(session.chapter)} session={session} update={setSession} back={()=>setScreen('home')}/>} {screen==='nhip'&&<Nhip back={()=>setScreen('home')}/>} {screen==='history'&&<Journey session={session} reset={()=>{setSession(initial);setScreen('home')}}/>}</main><footer><span>CHIẾU CHÈO SƯƠNG OAN</span><span>Bộ game vật lý · Đồng hành số</span></footer></div>}
function Home({session,chapter,start,ven,nhip}:{session:Session;chapter:Chapter;start:()=>void;ven:()=>void;nhip:()=>void}){return <div className="page"><div className="eyebrow"><span>PHIÊN CHƠI CỦA BẠN</span><span className="status"><i/> ĐANG Ở CHƯƠNG {session.chapter}</span></div><section className="welcome"><div><Kicker>DIGITAL COMPANION</Kicker><h1>Điều gì<br/><em>đã xảy ra?</em></h1><p className="lead">Cùng lật mở những lớp màn của câu chuyện.<br/>Hãy để bàn chơi dẫn đường.</p><button className="primary" onClick={start}>TIẾP TỤC CHƯƠNG {session.chapter}<ChevronRight/></button></div><div className="welcome-art"><div className="curtain left"/><div className="stage"><span>✦</span><strong>?</strong><small>Hành trình giải oan</small></div><div className="curtain right"/></div></section><section className="dashboard-grid"><article className="panel chapter-panel"><div className="panel-top"><div><Kicker>BẠN ĐANG Ở</Kicker><h2>Chương {session.chapter} <span>·</span> {chapter.title}</h2></div><BookOpen/></div><p className="muted">{chapter.theme}. Mỗi góc nhìn là một mảnh ghép.</p><div className="path">{chapters.map(c=><button key={c.n} className={c.n===session.chapter?'selected':''} disabled={c.n>1} onClick={start}><span>{c.n}</span>{c.short}</button>)}</div><button className="text-link" onClick={start}>Mở tình huống đang chơi <ChevronRight/></button></article><article className="panel score-panel"><Kicker>ĐIỂM PHIÊN CHƠI</Kicker><div className="scores"><div><strong>{String(session.oan).padStart(2,'0')}</strong><span>ĐIỂM OAN</span></div><div><strong>{String(session.hieu).padStart(2,'0')}</strong><span>HIỂU CHÈO</span></div></div><div className="limit"><span>AI VÉN MÀN</span><b>{session.usedVen.includes(session.chapter)?'0 / 1':'1 / 1'} lượt</b></div></article><article className="panel action-panel"><Kicker>TIẾP TỤC KHÁM PHÁ</Kicker><button onClick={ven}><Eye/><span><b>AI VÉN MÀN</b><small>Đặt câu hỏi · Chọn bằng chứng</small></span><ChevronRight/></button><button onClick={nhip}><Zap/><span><b>NHỊP – PHÁCH</b><small>Một thử thách nhỏ của chương</small></span><ChevronRight/></button></article></section></div>}
function OanFlow({card,session,update,back}:{card:Oan;session:Session;update:(s:Session)=>void;back:()=>void}){const [code,setCode]=useState('');const [result,setResult]=useState<'ok'|'bad'|null>(null);function check(){const ok=code===card.code;setResult(ok?'ok':'bad');if(ok&&!session.history.includes(card.id))update({...session,oan:session.oan+1,history:[...session.history,card.id]})}return <div className="page flow"><button className="back" onClick={back}>← BẢNG ĐIỀU KHIỂN</button><div className="flow-head"><Kicker>THẺ OAN · {card.id.toUpperCase()}</Kicker><span>CHƯƠNG {card.chapter}</span><h1>{card.title}</h1><p>{card.prompt}</p></div><div className="scan-layout"><div className="scene-card"><div className="scene-stamp">QR</div><Kicker>TÌNH HUỐNG</Kicker><h2>{card.scene}</h2><p>Điểm dừng này được mở từ QR trên Thẻ Oan. Bàn chơi vật lý vẫn là nơi câu chuyện tiếp tục.</p><div className="scene-lines"><span>THẺ OAN</span><b>{card.id}</b></div></div><div className="code-card"><Kicker>MÃ GÓC NHÌN</Kicker><label htmlFor="code">Nhập mã 4 chữ số trên Thẻ Góc Nhìn</label><input id="code" inputMode="numeric" maxLength={4} value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,''));setResult(null)}} placeholder="— — — —"/><button className="primary full" onClick={check} disabled={code.length!==4}>KIỂM TRA GÓC NHÌN <ChevronRight/></button>{result==='ok'&&<div className="result ok"><Check/><b>GIẢI OAN THÀNH CÔNG</b><span>Góc nhìn phù hợp. Oan không bị trừ.</span></div>}{result==='bad'&&<div className="result bad"><X/><b>GÓC NHÌN CHƯA PHÙ HỢP</b><span>Thử xem lại tình huống và góc nhìn của nhân vật.</span></div>}<p className="hint"><ShieldCheck/> Mã chỉ hợp lệ với đúng Thẻ Oan và chương hiện tại.</p></div></div></div>}
function VenFlow({chapter,locked,session,update,back}:{chapter:number;locked:boolean;session:Session;update:(s:Session)=>void;back:()=>void}){const [question,setQuestion]=useState('');const [started,setStarted]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [done,setDone]=useState(false);function begin(){if(question.trim()){setStarted(true);update({...session,usedVen:[...session.usedVen,chapter]})}}function finish(){setDone(true);if(selected.includes('e1')&&selected.includes('e2'))update({...session,hieu:session.hieu+1})}if(locked&&!started&&!done)return <div className="page flow locked-screen"><button className="back" onClick={back}>← BẢNG ĐIỀU KHIỂN</button><LockKeyhole/><Kicker>AI VÉN MÀN · CHƯƠNG {chapter}</Kicker><h1>Đã dùng lượt<br/><em>của chương này.</em></h1><p>Bạn chỉ có 1 lượt AI Vén Màn trong mỗi chương. Hãy tiếp tục suy luận từ những gì đã khám phá.</p><button className="secondary" onClick={back}>QUAY LẠI BÀN CHƠI</button></div>;return <div className="page flow"><button className="back" onClick={back}>← BẢNG ĐIỀU KHIỂN</button><div className="flow-head"><Kicker>AI VÉN MÀN · 1 / 1 LƯỢT</Kicker><h1>Đặt câu hỏi.<br/><em>Đừng vội tin.</em></h1><p>AI không trả lời thay bạn. Nó đưa ra những mảnh bằng chứng để bạn tự nhìn lại.</p></div>{!started?<div className="question-card"><label htmlFor="question">CÂU HỎI CỦA BẠN VỀ CHƯƠNG {chapter}</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ví dụ: Tại sao nhân vật này lại bị mọi người hiểu lầm?"/><button className="primary" onClick={begin} disabled={!question.trim()}>MỞ BẰNG CHỨNG <Eye/></button></div>:<div className="evidence-wrap"><div className="evidence-header"><span>Chọn những bằng chứng giúp trả lời câu hỏi.</span><b>{selected.length} đã chọn</b></div><div className="evidence-grid">{evidence.map(e=><button className={selected.includes(e.id)?'evidence selected':'evidence'} key={e.id} onClick={()=>setSelected(selected.includes(e.id)?selected.filter(x=>x!==e.id):[...selected,e.id])}><span className="check-box">{selected.includes(e.id)?'✓':''}</span><span><b>{e.title}</b><small>{e.text}</small></span></button>)}</div>{!done?<button className="primary" onClick={finish} disabled={!selected.length}>ĐÁNH GIÁ BẰNG CHỨNG <ChevronRight/></button>:<div className="explanation"><Sparkles/><Kicker>VÉN MÀN</Kicker><h2>{selected.includes('e1')&&selected.includes('e2')?'Bạn đã tìm đúng mạch chính.':'Bạn đã tìm được một phần câu trả lời.'}</h2><p>Hai bằng chứng trực tiếp giúp nối lời kể với dấu vết bên giếng. Lời đồn và màu áo tạo không khí cho câu chuyện, nhưng chưa đủ để kết luận.</p><div className="source-line"><BookOpen/> Nguồn: Hồ sơ trò chơi · Chương {chapter}</div></div>}</div>}</div>}
function Nhip({back}:{back:()=>void}){const [picked,setPicked]=useState<number[]>([]);const done=[1,3,4].every(x=>picked.includes(x))&&picked.length===3;return <div className="page flow"><button className="back" onClick={back}>← BẢNG ĐIỀU KHIỂN</button><div className="flow-head"><Kicker>THỬ THÁCH NHỊP – PHÁCH</Kicker><h1>Nghe nhịp.<br/><em>Nhìn phách.</em></h1><p>Một bài tập ngắn để cảm nhận cách sân khấu kể chuyện bằng chuyển động và âm thanh.</p></div><div className="rhythm-card"><div className="meter"><Clock3/><span>CHƯƠNG I · 01:20</span></div><p>Chọn các nhịp rơi vào phách mạnh:</p><div className="beats">{[1,2,3,4,5].map(n=><button key={n} className={picked.includes(n)?'beat picked':'beat'} onClick={()=>setPicked(picked.includes(n)?picked.filter(x=>x!==n):[...picked,n])}>{n}</button>)}</div>{done&&<div className="result ok"><Check/><b>NHỊP ĐÃ VÀO</b><span>Bạn đang lắng nghe bằng cả mắt và tai.</span></div>}<button className="text-link" onClick={()=>setPicked([])}><RotateCcw/> Làm lại</button></div></div>}
function Journey({session,reset}:{session:Session;reset:()=>void}){return <div className="page history-page"><div className="eyebrow"><span>HÀNH TRÌNH CỦA TÔI</span><span className="status"><i/> PHIÊN ĐANG LƯU</span></div><h1>Những gì bạn<br/><em>đã nhìn thấy.</em></h1><div className="history-grid"><div className="history-list">{chapters.map(c=><div className={c.n<session.chapter?'done':c.n===session.chapter?'now':'future'} key={c.n}><span>{c.n<session.chapter?'✓':c.n}</span><b>Chương {c.n}</b><small>{c.title}</small></div>)}</div><div className="history-score panel"><Kicker>TỔNG KẾT</Kicker><div className="scores"><div><strong>{String(session.oan).padStart(2,'0')}</strong><span>ĐIỂM OAN</span></div><div><strong>{String(session.hieu).padStart(2,'0')}</strong><span>HIỂU CHÈO</span></div></div><p className="muted">Mỗi câu trả lời đúng là một lần bạn nhìn câu chuyện bằng nhiều hơn một góc.</p><button className="text-link" onClick={reset}>Đặt lại phiên chơi <RotateCcw/></button></div></div></div>}

export default App
